#name = input("Enter your full name: ")
#phone_number = input("Enter your phoen number: ")

#result = len(name)
# first occurrence result = name.find("e")
# last occurrence result = name.rfind("e")
#name = name.capitalize()
#name = name.upper()
#name = name.lower()
#result = name.isdigit()
#result = name.isalpha()
#result = phone_number.count("-")
#phone_number = phone_number.replace("-", " ")
#print(phone_number)

#print(help(str))